In [ ]:
import numpy as np

In [ ]:
def tanh(x):
    """Función de activación tanh."""
    return np.tanh(x)

def tanh_derivative(x):
    """Derivada de la función tanh."""
    return 1 - np.tanh(x) ** 2

In [ ]:
X = np.array([
    [2.5, 3.5, -0.5],
    [4.0, -1.0, 0.5],
    [0.5, 1.5, 1.0],
    [3.0, 2.0, -1.5]
])

y = np.array([
    [1.0],
    [-1.0],
    [-1.0],
    [1.0]
])
print("x:", X)
print("y:", y)

x: [[ 2.5  3.5 -0.5]
 [ 4.  -1.   0.5]
 [ 0.5  1.5  1. ]
 [ 3.   2.  -1.5]]
y: [[ 1.]
 [-1.]
 [-1.]
 [ 1.]]


In [ ]:
W1 = np.array([
    [-0.34108091502837, 0.4875444774924518, -0.5786687891714137],
    [-0.7406084700295616, -0.5419469493214886, -0.7157868250555495],
    [-0.4315505068114813, -0.3888294993216346, -0.7260616380268912],
    [0.8544519713956533, -0.24436625968891335, -0.29745436944045234]
])
b1 = np.array([
    [0.42066411352123567],
    [-0.06842417572242421],
    [0.3917250492343052],
    [0.07861738679252617]
])

W2 = np.array([
    [0.8240668394757076, -0.7925535106179675, 0.856718957818575, 0.38940887530348656],
    [-0.8401491947426882, 0.6005090770290116, -0.710761829952594, -0.5376371931922113],
    [-0.9617475006414558, -0.1484109682541901, 0.315131084013728, 0.843811249537862],
    [0.7589476929906058, -0.6751635852663345, -0.05422983414165872, 0.43000805343850246]
])
b2 = np.array([
    [0.2807627460701372],
    [0.6705844066805486],
    [0.2750476238785533],
    [0.20918398742213418]
])

W3 = np.array([
    [-0.3547048938594579, -0.3011280508308256, 0.5691627652457749, -0.9665772078201607]
])
b3 = np.array([[0.9979425023631463]])

print("W1:", W1)
print("W2:", W2)
print("W3:", W3)
print("b1:", b1)
print("b2:", b2)
print("b3:", b3)

W1: [[-0.34108092  0.48754448 -0.57866879]
 [-0.74060847 -0.54194695 -0.71578683]
 [-0.43155051 -0.3888295  -0.72606164]
 [ 0.85445197 -0.24436626 -0.29745437]]
W2: [[ 0.82406684 -0.79255351  0.85671896  0.38940888]
 [-0.84014919  0.60050908 -0.71076183 -0.53763719]
 [-0.9617475  -0.14841097  0.31513108  0.84381125]
 [ 0.75894769 -0.67516359 -0.05422983  0.43000805]]
W3: [[-0.35470489 -0.30112805  0.56916277 -0.96657721]]
b1: [[ 0.42066411]
 [-0.06842418]
 [ 0.39172505]
 [ 0.07861739]]
b2: [[0.28076275]
 [0.67058441]
 [0.27504762]
 [0.20918399]]
b3: [[0.9979425]]


In [ ]:
# Capa Oculta 1
z1 = W1.dot(X.T) + b1
a1 = tanh(z1)
print("z1:", z1)
print("a1:", a1)

z1: [[ 1.56370189 -1.72053842  0.40277158  1.24051351]
 [-3.45886626 -2.84680452 -1.96743566 -2.30046325]
 [-1.68502365 -1.3086783  -1.13335609 -0.59149301]
 [ 1.50819259  3.59206435 -0.15816039  2.59942234]]
a1: [[ 0.91601815 -0.93792783  0.38231794  0.84560199]
 [-0.99802181 -0.99328777 -0.96165318 -0.98011465]
 [-0.93351042 -0.8639406  -0.81216475 -0.53096855]
 [ 0.90661778  0.99848409 -0.15685467  0.98901479]]


In [ ]:
# Capa Oculta 2
z2 = W2.dot(a1) + b2
a2 = tanh(z2)
print("z2:", z2)
print("a2:", a2)

z2: [[ 1.37989756 -0.0562545   0.60110234  1.68462892]
 [-0.52225653  0.93933922  0.43348545 -0.78275412]
 [ 0.01302297  1.89478974 -0.33821991  0.2744689 ]
 [ 2.0186989   0.64418511  1.1252113   1.96676804]]
a2: [[ 0.88092833 -0.05619523  0.5378335   0.93345966]
 [-0.47943973  0.73491851  0.40823003 -0.65428466]
 [ 0.01302223  0.95578918 -0.32588728  0.26777823]
 [ 0.96532513  0.56774241  0.80937396  0.96160293]]


In [ ]:
# Capa de Salida
z3 = W3.dot(a2) + b3
a3 = tanh(z3)
print("z3:", z3)
print("a3:", a3)

z3: [[-0.09580384  0.79180339 -0.28356452  0.08680918]]
a3: [[-0.0955118   0.65942944 -0.2762009   0.08659178]]


In [ ]:
error = a3 - y.T
delta3 = 2 * error * tanh_derivative(z3)
print("error:", error)
print("delta3:", delta3)

error: [[-1.0955118   1.65942944  0.7237991  -0.91340822]]
delta3: [[-2.17103598  1.87566244  1.33716536 -1.81311873]]


In [ ]:
loss = np.sum((y.T - a3)**2)
print(loss)

5.312051880293905


In [ ]:
delta2 = W3.T.dot(delta3) * tanh_derivative(z2)
print("delta2:", delta2)

delta2: [[ 0.17247053 -0.66320567 -0.33710103  0.08273963]
 [ 0.50348499 -0.25975528 -0.33555434  0.31225281]
 [-1.2354633   0.09230852  0.68023774 -0.95796281]
 [ 0.14300552 -1.2285945  -0.44579195  0.13199941]]


In [ ]:
delta1 = W2.T.dot(delta2) * tanh_derivative(z1)
print("delta1:", delta1)

delta1: [[ 0.16346314 -0.16233431 -0.84395226  0.23575742]
 [ 0.00099784  0.01586053  0.01998641  0.00689013]
 [-0.07805895 -0.07299838  0.06407392 -0.33038147]
 [-0.21089959 -0.00172385  0.42081974 -0.01938593]]


In [ ]:
dW3 = delta3.dot(a2.T)
db3 = np.sum(delta3, axis=1, keepdims=True)

dW2 = delta2.dot(a1.T)
db2 = np.sum(delta2, axis=1, keepdims=True)

dW1 = delta1.dot(X)
db1 = np.sum(delta1, axis=1, keepdims=True)

In [ ]:
learning_rate = 0.1
W1 -= learning_rate * dW1
b1 -= learning_rate * db1
W2 -= learning_rate * dW2
b2 -= learning_rate * db2
W3 -= learning_rate * dW3
b3 -= learning_rate * db3

In [ ]:
print("\nUpdated Weights and Biases:")
print(f"W1: {W1}")
print(f"W2: {W2}")
print(f"W3: {W3}")
print(f"b1: {b1}")
print(f"b2: {b2}")
print(f"b3: {b3}")


Updated Weights and Biases:
W1: [[-0.34554259  0.4935403  -0.44262008]
 [-0.7502685  -0.54508613 -0.71749508]
 [-0.28692567 -0.3123435  -0.78227928]
 [ 0.8926412  -0.22996956 -0.35290302]]
W2: [[ 0.75195582 -0.86552398  0.79253729  0.42652176]
 [-0.92420782  0.62329247 -0.69687519 -0.59349348]
 [-0.78492013 -0.29102007  0.2121559   1.05201748]
 [ 0.63649636 -0.81285838 -0.17622029  0.51966873]]
W3: [[-0.05558177 -0.71627873  0.48484404 -0.79736761]]
b1: [[ 0.48137072]
 [-0.07279767]
 [ 0.43346154]
 [ 0.05973635]]
b2: [[0.3552724 ]
 [0.64854159]
 [0.41713561]
 [0.34912214]]
b3: [[1.07507519]]


In [ ]:
print("\nBackward Propagation Results:")
print(f"Gradientes de los pesos y biases:")
print(f"dW1: {dW1}")
print(f"db1: {db1}")
print(f"dW2: {dW2}")
print(f"db2: {db2}")
print(f"dW3: {dW3}")
print(f"db3: {db3}")


Backward Propagation Results:
Gradientes de los pesos y biases:
dW1: [[ 0.04461671 -0.05995827 -1.36048712]
 [ 0.0966003   0.03139176  0.01708257]
 [-1.44624836 -0.76486001  0.56217641]
 [-0.38189232 -0.14396697  0.55448651]]
db1: [[-0.60706602]
 [ 0.04373491]
 [-0.41736489]
 [ 0.18881036]]
dW2: [[ 0.72111022  0.72970468  0.6418167  -0.37112887]
 [ 0.84058625 -0.22783392 -0.13886637  0.55856284]
 [-1.76827371  1.42609099  1.02975179 -2.08206226]
 [ 1.22451333  1.37694796  1.21990451 -0.8966068 ]]
db2: [[-0.74509654]
 [ 0.22042819]
 [-1.42087985]
 [-1.39938153]]
dW3: [[-2.99123123  4.15150677  0.84318722 -1.69209593]]
db3: [[-0.77132691]]
